---
title: "Getting Started"
date: "2025-10-03"
---

Ideally folks will have a chance to run through this prior to the workshop. It is one of the hurdles to getting going, but it gets easier!

## Software

The software that we will need is as follows. We recommend installing in this order as well. More detailed instructions can be found at each site, and [here](https://r4wrds.netlify.app/intro/m_install_r), (follow Steps 1 & 2).

### R

-   [R](https://cran.r-project.org)

-   [RStudio](https://posit.co/download/rstudio-desktop/)

-   [Quarto](https://quarto.org/docs/download/)

### Packages

The next step is to install a few packages, which are libraries of functions (more on these later) that we can use to do different things. We install packages available for all R users from an online repository called [CRAN](https://cran.r-project.org/), by pasting the following code into the RStudio Console window and hitting `ENTER`.

For our purposes we will be using a few packages, let's try to install them now.

```{r}
#| eval: false

# we make a concatenated list of packages
pkg_list <- c(
  "tidyverse", "janitor", "here", "sf", "tigris"
)
# then install each package in the list
install.packages(pkg_list)
```

## Live Code!

One way to make it less stressful is to always know whatever code we run/type will be available even after it disappears from the screen. We use a [**live code**](https://dl.dropbox.com/scl/fi/jvr4j9f5kszdswhr7xv5q/r_live_code.R?rlkey=94p4shtjlrssfiibc3vydj9en&dl=0) approach based on a shared script. Simply click on the [link](https://dl.dropbox.com/scl/fi/jvr4j9f5kszdswhr7xv5q/r_live_code.R?rlkey=94p4shtjlrssfiibc3vydj9en&dl=0) and refresh your browser (usually `Ctrl + R` or `Cmd + R`). You can then copy and save this code for your use as needed without worrying about missing something.

```{=html}
<iframe width="780" height="500" src="https://dl.dropbox.com/scl/fi/jvr4j9f5kszdswhr7xv5q/r_live_code.R?rlkey=94p4shtjlrssfiibc3vydj9en&dl=0" title="Live Code"></iframe>
```

## Getting Started!

[View slides in full screen](slides_getting_started.html)

```{=html}
<iframe class="slide-deck" src="slides_getting_started.html" height="420" width="747" style="border: 1px solid #2e3846;"></iframe>
```
